version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://amitpaul4006:bQrijN7EsQe3mcoz@cluster0.yxipk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - REDIS_HOST=redis
      - EMAIL_USER=amitpaul4006@gmail.com
      - EMAIL_APP_PASSWORD=sude iyan qbrx lrea
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
