[build]
  base = ""
  command = "cd client && npm install --force && npm run build"
  publish = "client/build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  directory = "api"
