[build]
  base = ""
  command = """
    npm install &&
    cd client && 
    rm -rf node_modules package-lock.json && 
    npm install --legacy-peer-deps &&
    npm run build
  """
  publish = "client/build"

[build.environment]
  NODE_VERSION = "16"
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max_old_space_size=4096"
  REACT_APP_API_URL = "/.netlify/functions/api"

[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  directory = "api"
  node_bundler = "esbuild"
